### ISSUE TITLE
With conditional formatting inside named range it throws exception if there was no data provided to range

### ISSUE THREAD

**Issue by kamil-szprych** [ClosedXML/ClosedXML.Report#186]
If you have a named range with `{{item.Something}}` inside to generate rows from list and you set any conditional formating for those dynamic rows then it throws error when you have empty list (without conditional formating it normally generates empty excel).

Exception:
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'The cells B1 and AQ3 are outside the range '__temp_buffer!A1:BA1'.')
   at ClosedXML.Excel.XLRangeBase.GetRange(XLAddress newFirstCellAddress, XLAddress newLastCellAddress)
   at ClosedXML.Excel.XLRangeBase.Range(IXLRangeAddress rangeAddress)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at ClosedXML.Report.Excel.XlExtensions.Relative(IXLRangeBase range, IXLRangeBase baseRange, IXLRangeBase targetBase)
   at ClosedXML.Report.Excel.XlExtensions.CopyRelative(IXLConditionalFormat format, IXLRangeBase fromRange, IXLRangeBase toRange, Boolean expand)
   at ClosedXML.Report.Excel.TempSheetBuffer.AddConditionalFormats(IEnumerable`1 formats, IXLRangeBase fromRange, IXLRangeBase toRange)
   at ClosedXML.Report.RangeTemplate.VerticalTable(Object[] items, FormulaEvaluator evaluator)
   at ClosedXML.Report.RangeTemplate.Generate(Object[] items)
   at ClosedXML.Report.RangeInterpreter.EvaluateValues(IXLRange range, Parameter[] pars)
   at ClosedXML.Report.RangeInterpreter.Evaluate(IXLRange range)
   at ClosedXML.Report.XLTemplate.Generate()
   at 
```

It seems that if there is no data in range then it has wrong info about range addresses or something?

**Comment by b0bi79** [comment]
The problem is not reproducible
