### ISSUE TITLE
MissingMethodException on new XLTemplate()

### ISSUE THREAD

**Issue by ShelestSergey** [ClosedXML/ClosedXML.Report#326]
When I'm trying to open template, exception raise:
System.MissingMethodException
  HResult=0x80131513
  Message=Метод не найден: "System.Collections.Generic.IEnumerable`1<SixLabors.Fonts.GlyphMetrics> SixLabors.Fonts.FontMetrics.GetGlyphMetrics(SixLabors.Fonts.Unicode.CodePoint, SixLabors.Fonts.ColorFontSupport)".
  Source=ClosedXML
  StackTrace:
   at ClosedXML.Graphics.DefaultGraphicEngine.CalculateMaxDigitWidth(MetricId metricId)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at ClosedXML.Graphics.DefaultGraphicEngine.GetMaxDigitWidth(IXLFontBase fontBase, Double dpiX)
   at ClosedXML.Excel.XLWorkbook.CalculateColumnWidth(Double charWidth, IXLFont font, XLWorkbook workbook)
   at ClosedXML.Excel.XLWorkbook.LoadSpreadsheetDocument(SpreadsheetDocument dSpreadsheet)
   at ClosedXML.Excel.XLWorkbook.LoadSheets(String fileName)
   at ClosedXML.Excel.XLWorkbook..ctor(String file, LoadOptions loadOptions)
   at ClosedXML.Excel.XLWorkbook..ctor(String file)
   at ClosedXML.Report.XLTemplate..ctor(String fileName) in D:\Temp\DXApplication2\ClosedXML.Report-develop\ClosedXML.Report\XLTemplate.cs:line 63
   at DXApplication2.Form1.simpleButton1_Click(Object sender, EventArgs e) in D:\Temp\DXApplication2\DXApplication2\Form1.cs:line 34
But file successfuly opens on 2.0.6 version of ClosedXML.Report and ClosedXML 097 version.
I tried all variations of ClosedXML.Report and ClosedXML from 2.0.7 version.

**Comment by ShelestSergey** [comment]
So I tried to create template from project, using example from wiki.
It doesnt work too.  Same error. 

Maybe I do something wrong?

**Comment by jahav** [comment]
@ShelestSergey That is a result of buggy behavior of NuGet for package.config references (SixLabors.Fonts has released version 1.0.0 with breaking changes and thus declared reference 1.0.0-beta19 is ignored and nuget selects 1.0.0 leading to version mismatch).

Use sdk style project or try some workarounds from https://github.com/ClosedXML/ClosedXML/issues/2146

I have pushed ClosedXML version 0.102.1 that references version SixLabors.Fonts version 1.0.0 (**non**-beta), but I have at most cursory knowledge of ClosedXML.Report, so it might not work due to breaking changes from [0.101 to 0.102](https://docs.closedxml.io/en/latest/migrations/migrate-to-0.102.html).
