### ISSUE TITLE
Method not found: ClosedXML.Excel.IXLRange ClosedXML.Excel.IXLPivotTable.get_SourceRange()

### ISSUE THREAD

**Issue by Int32Overflow** [ClosedXML/ClosedXML.Report#332]
A "Method not found" error occurs.

**Version:** 
- ClosedXML: 0.102.1
- ClosedXML.Report: 0.2.8

**Message:** `Methode not found: "ClosedXML.Excel.IXLRange ClosedXML.Excel.IXLPivotTable.get_SourceRange()".`
**Source:** `ClosedXML.Report`
**Call Stack:** 
```
   at ClosedXML.Report.RangeInterpreter.EvaluateValues(IXLRange range, Parameter[] pars)
   at ClosedXML.Report.RangeInterpreter.Evaluate(IXLRange range)
   at ClosedXML.Report.XLTemplate.Generate()
```

Template: [ReturnReport.xlsx](https://github.com/ClosedXML/ClosedXML.Report/files/12726150/ReturnReport.xlsx)

**Comment by disco-dolphin** [comment]
Try this... #324. Cheers.

**Comment by Pankraty** [comment]
Try ClosedXML.Report 0.2.11 or 0.2.12-rc
