### ISSUE TITLE
Comma in Worksheet Name on Template causes InvalidOperationException

### ISSUE THREAD

**Issue by DukeOfDelmar** [ClosedXML/ClosedXML.Report#47]
1. Create a template
2. Add a second worksheet
3. Rename the sheet to a name containing a comma
4. Add a valid vertical table definition to the sheet
5. Attempt to apply the template
6. Exception occurs:
System.InvalidOperationException
  HResult=0x80131509
  Message=Sequence contains no matching element
  Source=System.Core
  StackTrace:
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at ClosedXML.Excel.XLNamedRange.<get_Ranges>b__9_3(<>f__AnonymousType3`2 <>h__TransparentIdentifier0)
   at System.Linq.Enumerable.<>c__DisplayClass7_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at ClosedXML.Excel.XLNamedRange.get_Ranges()
   at ClosedXML.Report.Excel.XlExtensions.<>c__DisplayClass7_0.<GetContainingNames>b__0(IXLNamedRange x)
   at System.Linq.Enumerable.<>c__DisplayClass6_0`1.<CombinePredicates>b__0(TSource x)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at ClosedXML.Report.RangeInterpreter.ParseTags(IXLRange range, String rangeName)
   at ClosedXML.Report.RangeInterpreter.Evaluate(IXLRange range)
   at ClosedXML.Report.XLTemplate.Generate()
...

**Comment by b0bi79** [comment]
This is a bug in ClosedXML that has been fixed in recent versions. We are currently working to support ClosedXML.Report the latest version of ClosedXML.
